/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SchemaFormatsRouteImport } from './routes/schema-formats'
import { Route as RestApiRouteImport } from './routes/rest-api'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AuthenticatedPresetsRouteImport } from './routes/_authenticated/presets'
import { Route as AuthenticatedKeysRouteImport } from './routes/_authenticated/keys'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicV1UsageRouteImport } from './routes/api/public/v1/usage'
import { Route as ApiPublicV1InsertRouteImport } from './routes/api/public/v1/insert'
import { Route as ApiPublicV1GenerateRouteImport } from './routes/api/public/v1/generate'
import { Route as ApiPublicV1FormatsRouteImport } from './routes/api/public/v1/formats'
import { Route as ApiPublicV1AnalyzeRouteImport } from './routes/api/public/v1/analyze'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaFormatsRoute = SchemaFormatsRouteImport.update({
  id: '/schema-formats',
  path: '/schema-formats',
  getParentRoute: () => rootRouteImport,
} as any)
const RestApiRoute = RestApiRouteImport.update({
  id: '/rest-api',
  path: '/rest-api',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPresetsRoute = AuthenticatedPresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKeysRoute = AuthenticatedKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicV1UsageRoute = ApiPublicV1UsageRouteImport.update({
  id: '/api/public/v1/usage',
  path: '/api/public/v1/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1InsertRoute = ApiPublicV1InsertRouteImport.update({
  id: '/api/public/v1/insert',
  path: '/api/public/v1/insert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1GenerateRoute = ApiPublicV1GenerateRouteImport.update({
  id: '/api/public/v1/generate',
  path: '/api/public/v1/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1FormatsRoute = ApiPublicV1FormatsRouteImport.update({
  id: '/api/public/v1/formats',
  path: '/api/public/v1/formats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AnalyzeRoute = ApiPublicV1AnalyzeRouteImport.update({
  id: '/api/public/v1/analyze',
  path: '/api/public/v1/analyze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/api-reference': typeof ApiReferenceRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRoute
  '/examples': typeof ExamplesRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/playground': typeof PlaygroundRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/rest-api': typeof RestApiRoute
  '/schema-formats': typeof SchemaFormatsRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/presets': typeof AuthenticatedPresetsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/public/v1/analyze': typeof ApiPublicV1AnalyzeRoute
  '/api/public/v1/formats': typeof ApiPublicV1FormatsRoute
  '/api/public/v1/generate': typeof ApiPublicV1GenerateRoute
  '/api/public/v1/insert': typeof ApiPublicV1InsertRoute
  '/api/public/v1/usage': typeof ApiPublicV1UsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/api-reference': typeof ApiReferenceRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRoute
  '/examples': typeof ExamplesRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/playground': typeof PlaygroundRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/rest-api': typeof RestApiRoute
  '/schema-formats': typeof SchemaFormatsRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/presets': typeof AuthenticatedPresetsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/public/v1/analyze': typeof ApiPublicV1AnalyzeRoute
  '/api/public/v1/formats': typeof ApiPublicV1FormatsRoute
  '/api/public/v1/generate': typeof ApiPublicV1GenerateRoute
  '/api/public/v1/insert': typeof ApiPublicV1InsertRoute
  '/api/public/v1/usage': typeof ApiPublicV1UsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/api-reference': typeof ApiReferenceRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRoute
  '/examples': typeof ExamplesRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/playground': typeof PlaygroundRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/rest-api': typeof RestApiRoute
  '/schema-formats': typeof SchemaFormatsRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/keys': typeof AuthenticatedKeysRoute
  '/_authenticated/presets': typeof AuthenticatedPresetsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/public/v1/analyze': typeof ApiPublicV1AnalyzeRoute
  '/api/public/v1/formats': typeof ApiPublicV1FormatsRoute
  '/api/public/v1/generate': typeof ApiPublicV1GenerateRoute
  '/api/public/v1/insert': typeof ApiPublicV1InsertRoute
  '/api/public/v1/usage': typeof ApiPublicV1UsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/api-reference'
    | '/changelog'
    | '/docs'
    | '/examples'
    | '/integrations'
    | '/login'
    | '/mcp'
    | '/playground'
    | '/pricing'
    | '/product'
    | '/rest-api'
    | '/schema-formats'
    | '/signup'
    | '/dashboard'
    | '/history'
    | '/keys'
    | '/presets'
    | '/api/mcp'
    | '/api/public/v1/analyze'
    | '/api/public/v1/formats'
    | '/api/public/v1/generate'
    | '/api/public/v1/insert'
    | '/api/public/v1/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/api-reference'
    | '/changelog'
    | '/docs'
    | '/examples'
    | '/integrations'
    | '/login'
    | '/mcp'
    | '/playground'
    | '/pricing'
    | '/product'
    | '/rest-api'
    | '/schema-formats'
    | '/signup'
    | '/dashboard'
    | '/history'
    | '/keys'
    | '/presets'
    | '/api/mcp'
    | '/api/public/v1/analyze'
    | '/api/public/v1/formats'
    | '/api/public/v1/generate'
    | '/api/public/v1/insert'
    | '/api/public/v1/usage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/agents'
    | '/api-reference'
    | '/changelog'
    | '/docs'
    | '/examples'
    | '/integrations'
    | '/login'
    | '/mcp'
    | '/playground'
    | '/pricing'
    | '/product'
    | '/rest-api'
    | '/schema-formats'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/keys'
    | '/_authenticated/presets'
    | '/api/mcp'
    | '/api/public/v1/analyze'
    | '/api/public/v1/formats'
    | '/api/public/v1/generate'
    | '/api/public/v1/insert'
    | '/api/public/v1/usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  ApiReferenceRoute: typeof ApiReferenceRoute
  ChangelogRoute: typeof ChangelogRoute
  DocsRoute: typeof DocsRoute
  ExamplesRoute: typeof ExamplesRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRoute
  RestApiRoute: typeof RestApiRoute
  SchemaFormatsRoute: typeof SchemaFormatsRoute
  SignupRoute: typeof SignupRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiPublicV1AnalyzeRoute: typeof ApiPublicV1AnalyzeRoute
  ApiPublicV1FormatsRoute: typeof ApiPublicV1FormatsRoute
  ApiPublicV1GenerateRoute: typeof ApiPublicV1GenerateRoute
  ApiPublicV1InsertRoute: typeof ApiPublicV1InsertRoute
  ApiPublicV1UsageRoute: typeof ApiPublicV1UsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema-formats': {
      id: '/schema-formats'
      path: '/schema-formats'
      fullPath: '/schema-formats'
      preLoaderRoute: typeof SchemaFormatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rest-api': {
      id: '/rest-api'
      path: '/rest-api'
      fullPath: '/rest-api'
      preLoaderRoute: typeof RestApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/presets': {
      id: '/_authenticated/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof AuthenticatedPresetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/keys': {
      id: '/_authenticated/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AuthenticatedKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/v1/usage': {
      id: '/api/public/v1/usage'
      path: '/api/public/v1/usage'
      fullPath: '/api/public/v1/usage'
      preLoaderRoute: typeof ApiPublicV1UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/insert': {
      id: '/api/public/v1/insert'
      path: '/api/public/v1/insert'
      fullPath: '/api/public/v1/insert'
      preLoaderRoute: typeof ApiPublicV1InsertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/generate': {
      id: '/api/public/v1/generate'
      path: '/api/public/v1/generate'
      fullPath: '/api/public/v1/generate'
      preLoaderRoute: typeof ApiPublicV1GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/formats': {
      id: '/api/public/v1/formats'
      path: '/api/public/v1/formats'
      fullPath: '/api/public/v1/formats'
      preLoaderRoute: typeof ApiPublicV1FormatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/analyze': {
      id: '/api/public/v1/analyze'
      path: '/api/public/v1/analyze'
      fullPath: '/api/public/v1/analyze'
      preLoaderRoute: typeof ApiPublicV1AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedKeysRoute: typeof AuthenticatedKeysRoute
  AuthenticatedPresetsRoute: typeof AuthenticatedPresetsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedKeysRoute: AuthenticatedKeysRoute,
  AuthenticatedPresetsRoute: AuthenticatedPresetsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  ApiReferenceRoute: ApiReferenceRoute,
  ChangelogRoute: ChangelogRoute,
  DocsRoute: DocsRoute,
  ExamplesRoute: ExamplesRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PlaygroundRoute: PlaygroundRoute,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRoute,
  RestApiRoute: RestApiRoute,
  SchemaFormatsRoute: SchemaFormatsRoute,
  SignupRoute: SignupRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiPublicV1AnalyzeRoute: ApiPublicV1AnalyzeRoute,
  ApiPublicV1FormatsRoute: ApiPublicV1FormatsRoute,
  ApiPublicV1GenerateRoute: ApiPublicV1GenerateRoute,
  ApiPublicV1InsertRoute: ApiPublicV1InsertRoute,
  ApiPublicV1UsageRoute: ApiPublicV1UsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
